# Generated by Django 3.1.3 on 2020-11-08 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0002_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 5, 14, 44, 616990, tzinfo=utc)),
        ),
    ]
