# Generated by Django 3.1.3 on 2020-11-08 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DayPlanner', '0003_auto_20201108_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 5, 56, 0, 24834, tzinfo=utc)),
        ),
    ]
